### ISSUE TITLE
定位保存

### ISSUE THREAD

**Issue by panshijian** [JingheLee/UIAutomatorViewer#1]
Error while parsing UI hierarchy XML file: null[Ljava.lang.StackTraceElement;@7abaef3a
Error while parsing UI hierarchy XML file: null[Ljava.lang.StackTraceElement;@7abaef3a

**Comment by JingheLee** [comment]
是否有复现步骤？

**Comment by JingheLee** [comment]
> Error while parsing UI hierarchy XML file: null[Ljava.lang.StackTraceElement;@7abaef3a Error while parsing UI hierarchy XML file: null[Ljava.lang.StackTraceElement;@7abaef3a
Whether there are recurrence steps？
