### ISSUE TITLE
how to resolve below error

### ISSUE THREAD

**Issue by vbpatel73** [JingheLee/UIAutomatorViewer#2]
`127.0.0.1 - - [14/Mar/2023 09:34:42] "POST /api/android/device/dump HTTP/1.1" 500 -
127.0.0.1 - - [14/Mar/2023 09:36:57] "GET /api/android/device/list HTTP/1.1" 200 -
[W 230314 09:36:57 __init__:492] [pid:33760] [R58R36842KN] jsonrpc call got: 0 Unknown error: <Attempt to read from field 'int android.accessibilityservice.AccessibilityServiceInfo.flags' on a null object reference in method 'void androidx.test.uiautomator.UiDevice.setCompressedLayoutHeirarchy(boolean)'> data: {'exceptionTypeName': 'java.lang.NullPointerException', 'message': "Attempt to read from field 'int android.accessibilityservice.AccessibilityServiceInfo.flags' on a null object reference in method 'void androidx.test.uiautomator.UiDevice.setCompressedLayoutHeirarchy(boolean)'"}, method: dumpWindowHierarchy`

**Comment by WALL-1** [comment]
This bug throw from uiautomator2 project,if alway exists please goto uiautomator2 project get help.
